version: '3'
services:
  database:
    image: mysql:5
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kwetter
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user